server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/auth_db}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      registration-initiated: registration-initiated
      registration-completed: registration-completed
    consumer:
      group-id: auth-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: off