server:
  port: 8000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      email-send: email-send
      orchestrator: orchestrator

logging:
  level:
    org:
      apache:
        kafka: off