server:
  port: 8090

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/email_db}


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      email-success: email-success
      email-fail: email-fail
    consumer:
      group-id: email-service-group
      auto-offset-reset: latest

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

logging:
  level:
    org:
      apache:
        kafka: off