server:
  port: 8090

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/email_db}


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      email-success: email-success
      email-fail: email-fail
    consumer:
      group-id: email-service-group
      auto-offset-reset: latest

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_SERVER_PORT:587}
    username: ${MAIL_USERNAME:""}
    password: ${MAIL_PASSWORD:""}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true

logging:
  level:
    org:
      apache:
        kafka: off